<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Assign_button</name>
   <tag></tag>
   <elementGuidId>2dc14129-01a0-4e12-84aa-cb88ee9f8fe7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#but_select > span.mat-button-wrapper</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='but_select']/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>89e0e824-f3fd-4e0b-bf77-731be6b09cb1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mat-button-wrapper</value>
      <webElementGuid>639744c4-eeed-4729-9d61-bb7a895cbd99</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Assign </value>
      <webElementGuid>e9d6c6ab-fbec-466c-a531-2b4e8fe9f301</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mat-dialog-0&quot;)/ocdiplaccomponent[@class=&quot;ng-star-inserted&quot;]/s4-dialog-card[@class=&quot;s4-dialog-card&quot;]/s4-dialog-card-actions[@class=&quot;s4-dialog-card-actions&quot;]/mat-dialog-actions[@class=&quot;mat-dialog-actions&quot;]/div[@class=&quot;btn-mt9&quot;]/s4-button[@id=&quot;but_select&quot;]/button[@id=&quot;but_select&quot;]/span[@class=&quot;mat-button-wrapper&quot;]</value>
      <webElementGuid>284403eb-abae-40d6-97bc-bd1c9233ae35</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//button[@id='but_select']/span</value>
      <webElementGuid>4f4434ca-5b5f-4af5-ade5-8b1b922eef99</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Rows per page'])[5]/following::span[10]</value>
      <webElementGuid>08b87af4-deff-4214-a4dd-a623357ef63c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Exit'])[1]/preceding::span[3]</value>
      <webElementGuid>45f5118c-0106-4c74-bd0d-df37c15c7ac4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Assign']/parent::*</value>
      <webElementGuid>6decab04-f62b-4030-887a-2f0cead1a9b5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//mat-dialog-actions/div/s4-button/button/span</value>
      <webElementGuid>31e177c9-e889-4555-a94c-e6312b3480fb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = ' Assign ' or . = ' Assign ')]</value>
      <webElementGuid>6fc7b9f9-7953-4af7-be7e-ed080bb22f9b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
