<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>CasePlanRole_dropdown</name>
   <tag></tag>
   <elementGuidId>db9dc637-bcb8-44ca-9470-8806a62b66dd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.ag-row-even.ag-row.ag-row-level-0.middle.ag-row-position-absolute.ag-row-first.ag-row-last.ag-row-selected.ag-row-focus.ag-row-hover.ag-row-not-inline-editing > div.ag-cell-value.ag-cell.ag-cell-not-inline-editing.ag-cell-normal-height.ag-cell-focus.ag-cell-range-selected.ag-cell-range-selected-1.ag-cell-range-single-cell</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//div[@id='gridContainer']/ag-grid-angular/div/div[2]/div[2]/div[3]/div[2]/div/div/div/div[2])[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>fa24292f-575b-4854-9be9-81860db1d18d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>comp-id</name>
      <type>Main</type>
      <value>784</value>
      <webElementGuid>71953733-261a-4110-b615-ffd7b6deca40</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ag-cell-value ag-cell ag-cell-not-inline-editing ag-cell-normal-height ag-cell-focus ag-cell-range-selected ag-cell-range-selected-1 ag-cell-range-single-cell</value>
      <webElementGuid>c06c716d-2c88-427c-9f88-a03b21c5e84e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-colindex</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>5e155af8-f3ee-4782-9295-3f89999fdf1b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>885caa45-6368-4cd5-931f-32337fac198d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>col-id</name>
      <type>Main</type>
      <value>casePlanRole</value>
      <webElementGuid>9ab4750a-89ab-4228-9536-cac84d0a6faa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>gridcell</value>
      <webElementGuid>64c8b50d-62ce-42ad-a5c5-0d20a567f685</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-selected</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>214ec49e-7cc8-4573-b172-588f6b4ebacb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>  keyboard_arrow_down</value>
      <webElementGuid>de6842b9-d943-4675-8cc6-0e824bd327dc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cdk-accordion-child-6&quot;)/div[@class=&quot;mat-expansion-panel-body ng-tns-c182-68&quot;]/div[@class=&quot;ng-tns-c182-68&quot;]/div[1]/s4-grid[1]/div[@id=&quot;gridContainer&quot;]/ag-grid-angular[@class=&quot;ag-theme-alpine&quot;]/div[@class=&quot;ag-root-wrapper ag-layout-auto-height ag-ltr&quot;]/div[@class=&quot;ag-root-wrapper-body ag-layout-auto-height ag-focus-managed&quot;]/div[@class=&quot;ag-root ag-unselectable ag-layout-auto-height&quot;]/div[@class=&quot;ag-body-viewport ag-layout-auto-height ag-row-animation ag-has-focus&quot;]/div[@class=&quot;ag-center-cols-clipper&quot;]/div[@class=&quot;ag-center-cols-viewport&quot;]/div[@class=&quot;ag-center-cols-container&quot;]/div[@class=&quot;ag-row-even ag-row ag-row-level-0 middle ag-row-position-absolute ag-row-first ag-row-last ag-row-selected ag-row-focus ag-row-hover ag-row-not-inline-editing&quot;]/div[@class=&quot;ag-cell-value ag-cell ag-cell-not-inline-editing ag-cell-normal-height ag-cell-focus ag-cell-range-selected ag-cell-range-selected-1 ag-cell-range-single-cell&quot;]</value>
      <webElementGuid>624deb35-8cc0-40f6-938e-0bf9003f6190</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>(//div[@id='gridContainer']/ag-grid-angular/div/div[2]/div[2]/div[3]/div[2]/div/div/div/div[2])[2]</value>
      <webElementGuid>91045408-9608-4991-a32c-b93d679361de</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='End Date'])[3]/following::div[20]</value>
      <webElementGuid>d778baa6-a2e4-423f-8e01-e5c6c0af1ae7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Start Date'])[2]/following::div[27]</value>
      <webElementGuid>473d8094-b40a-43a2-ae70-abf1f8e14b2d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='true'])[1]/preceding::div[5]</value>
      <webElementGuid>3f4b5738-cb88-42b6-b529-907adb7fd759</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='to'])[5]/preceding::div[32]</value>
      <webElementGuid>3c6d76b6-865e-4563-9339-b25e9ee98b3b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//mat-dialog-content/s4-panel/div/div/div/mat-expansion-panel/div/div/div[2]/div/s4-grid/div/ag-grid-angular/div/div[2]/div[2]/div[3]/div[2]/div/div/div/div[2]</value>
      <webElementGuid>e63a2678-a7cd-4a6e-b2ad-0060d61c63cc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = '  keyboard_arrow_down' or . = '  keyboard_arrow_down')]</value>
      <webElementGuid>6da6d00a-0d67-42be-84c0-3e5f752f9a13</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
