<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Staff Name LOV</name>
   <tag></tag>
   <elementGuidId>234f2be6-ac38-4385-860e-4a4d1d1070c8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//li/span[contains(text(), &quot;DWIVEDI, ANJU&quot;)]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//mat-option[@id='mat-option-142']/span/li/span[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>8a80e6a5-e5e5-47ab-b3b7-aecb95112240</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-star-inserted</value>
      <webElementGuid>56dde685-eefd-4b03-b783-39febc972701</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>4630</value>
      <webElementGuid>29cd1408-9e8d-4925-93ce-65efe1e6cd6c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//li/span[contains(text(), &quot;DWIVEDI, ANJU&quot;)]</value>
      <webElementGuid>98ad1dcc-db14-48a3-b75e-8c68feaf992e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//mat-option[@id='mat-option-159']/span/li/span[2]</value>
      <webElementGuid>64d966df-6d3f-4ac9-8b70-96f43b727cd8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='DWIVEDI, ANJU'])[1]/following::span[1]</value>
      <webElementGuid>51684368-3494-47f0-8172-89c5405bfe47</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Allen, Lorie'])[1]/following::span[4]</value>
      <webElementGuid>82cbfd8c-9c2e-4913-8fd9-fbeff40160dd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ELITEV4USER3, ELITESTAFF1'])[1]/preceding::span[1]</value>
      <webElementGuid>b7e9a6d6-9d9a-4b6c-834f-89b95fc53b4b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='FASHOGBON, JIBOLA'])[1]/preceding::span[4]</value>
      <webElementGuid>d78bcaf6-5993-4c8b-bb3e-0696ff9ffbef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='4630']/parent::*</value>
      <webElementGuid>2649247d-603f-4615-81ae-060bc16b875c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//mat-option[7]/span/li/span[2]</value>
      <webElementGuid>369cc35d-8515-434c-a8a0-9a9536b6c6e4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = '4630' or . = '4630')]</value>
      <webElementGuid>a571017f-3a61-4c2b-a3c3-c76ff92f7446</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
