<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Status_dropdown</name>
   <tag></tag>
   <elementGuidId>264c79fb-ccf3-4968-8266-68cbe4dad90b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//ag-grid-angular[@id='caspln']/div/div[2]/div[2]/div[3]/div[2]/div/div/div/div[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>204430cc-5775-453c-b97d-e4d1b8389caf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>comp-id</name>
      <type>Main</type>
      <value>559</value>
      <webElementGuid>cf776392-609d-4002-8a17-dd58166dec07</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ag-cell-value ag-cell ag-cell-not-inline-editing ag-cell-normal-height</value>
      <webElementGuid>159cafea-349b-44df-b5d0-e55d6ad4af48</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-colindex</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>6f61ca69-b331-4dd4-8e8a-4f9ac89330a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>f4d6b452-9b6d-4ee6-ae6f-ade01ec9bcb1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>col-id</name>
      <type>Main</type>
      <value>casePlanStatusDesc</value>
      <webElementGuid>cf3bbf8a-8afc-46c1-aab2-2e281319020b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>gridcell</value>
      <webElementGuid>4f16a614-8910-4cb1-b31c-38c6ddcae6ab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>  keyboard_arrow_down</value>
      <webElementGuid>f51fc446-a86d-434e-8161-133747b90893</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cdk-accordion-child-2&quot;)/div[@class=&quot;mat-expansion-panel-body ng-tns-c182-29&quot;]/div[@class=&quot;ng-tns-c182-29&quot;]/div[1]/s4-grid[1]/div[@id=&quot;gridContainer&quot;]/ag-grid-angular[@id=&quot;caspln&quot;]/div[@class=&quot;ag-root-wrapper ag-layout-auto-height ag-ltr&quot;]/div[@class=&quot;ag-root-wrapper-body ag-layout-auto-height ag-focus-managed&quot;]/div[@class=&quot;ag-root ag-unselectable ag-layout-auto-height&quot;]/div[@class=&quot;ag-body-viewport ag-layout-auto-height ag-row-animation ag-has-focus&quot;]/div[@class=&quot;ag-center-cols-clipper&quot;]/div[@class=&quot;ag-center-cols-viewport&quot;]/div[@class=&quot;ag-center-cols-container&quot;]/div[@class=&quot;ag-row-even ag-row ag-row-level-0 middle ag-row-position-absolute ag-row-first ag-row-last ag-row-selected ag-row-focus ag-row-hover&quot;]/div[@class=&quot;ag-cell-value ag-cell ag-cell-not-inline-editing ag-cell-normal-height&quot;]</value>
      <webElementGuid>d807f118-9d50-4348-a44f-b1cd2bd40efa</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ag-grid-angular[@id='caspln']/div/div[2]/div[2]/div[3]/div[2]/div/div/div/div[2]</value>
      <webElementGuid>1fff49b3-1b83-4753-b2f7-a3a0eced69cb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Verified'])[1]/following::div[17]</value>
      <webElementGuid>ac5125b1-c6c7-451e-ab44-3ffa8fd9c3c9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Next Review Date'])[1]/following::div[24]</value>
      <webElementGuid>3c5abeec-dfe6-4b25-bc7b-1b69943746d2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Hobart Reception Prison'])[1]/preceding::div[4]</value>
      <webElementGuid>90f629f8-c44e-4376-8141-6ab219e1206c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='to'])[2]/preceding::div[38]</value>
      <webElementGuid>fe6d84df-37af-427b-a798-1fbea86083f8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[2]/div/div/div/div[2]</value>
      <webElementGuid>1579b71c-eaa4-44e1-a194-4a0e842a75fb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = '  keyboard_arrow_down' or . = '  keyboard_arrow_down')]</value>
      <webElementGuid>275197ae-0e56-436c-97f7-65f95212aeca</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
