<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>AmendCaseNote_text</name>
   <tag></tag>
   <elementGuidId>4fde07ed-8900-4f8a-8227-7a9607a4023b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.mat-form-field-infix.ng-tns-c87-42 > #textcase_note_text</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//textarea[@id='textcase_note_text'])[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>1c717cc3-76cb-4faf-a343-9fe808dc7c82</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mat-input-element mat-form-field-autofill-control ng-tns-c87-42 ng-untouched ng-pristine ng-valid cdk-text-field-autofill-monitored</value>
      <webElementGuid>5344a774-8490-45f4-859e-eb9b264d054f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>3a9bcdf0-8027-4d03-8fb2-500fd367ace1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>textcase_note_text</value>
      <webElementGuid>9a60430c-afc6-4eda-9b30-78b6eb51dbac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>67909160-eb59-4f42-a8d8-c3bd67baad55</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>69dce090-4093-48dd-9b78-c3e3da335216</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>31735</value>
      <webElementGuid>2b1fc226-e2de-4005-a58d-498ff7df8b1c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cdk-accordion-child-5&quot;)/div[@class=&quot;mat-expansion-panel-body ng-tns-c182-38&quot;]/div[@class=&quot;ng-tns-c182-38&quot;]/div[1]/s4-textarea[@id=&quot;textcase_note_text&quot;]/mat-form-field[@class=&quot;mat-form-field component-full-width ng-tns-c87-42 mat-primary mat-form-field-type-mat-input mat-form-field-appearance-legacy mat-form-field-can-float mat-form-field-hide-placeholder ng-untouched ng-pristine ng-valid ng-star-inserted&quot;]/div[@class=&quot;mat-form-field-wrapper ng-tns-c87-42&quot;]/div[@class=&quot;mat-form-field-flex ng-tns-c87-42&quot;]/div[@class=&quot;mat-form-field-infix ng-tns-c87-42&quot;]/textarea[@id=&quot;textcase_note_text&quot;]</value>
      <webElementGuid>0deacf90-0335-470a-8c02-05c7554f5804</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//textarea[@id='textcase_note_text'])[2]</value>
      <webElementGuid>b1bebb06-abc0-49c7-a6fc-b7e76d2a2de4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>(//s4-textarea[@id='textcase_note_text']/mat-form-field/div/div/div/textarea)[2]</value>
      <webElementGuid>edf9baea-6c6d-49d2-bae4-d22769562748</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Case Note Text'])[2]/following::textarea[1]</value>
      <webElementGuid>24f8cb4b-e745-4759-939c-c4e5b944f769</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Amend Case Note'])[1]/following::textarea[1]</value>
      <webElementGuid>29e80c14-6086-4da3-9611-e95f47b4061d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//s4-panel[2]/div/div/div/mat-expansion-panel/div/div/div/div/s4-textarea/mat-form-field/div/div/div/textarea</value>
      <webElementGuid>803cc94c-ef11-4da1-bfff-c0d8f23f17ee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@id = 'textcase_note_text']</value>
      <webElementGuid>0c4c6300-be34-4194-9333-aa197648fda8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
