<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>AmendCaseNote_Button</name>
   <tag></tag>
   <elementGuidId>920fa734-7766-4ef1-acf3-01477154637d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.edit.ng-star-inserted</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//ag-grid-angular[@id='offnotestab']/div/div[2]/div[2]/div[3]/div[2]/div/div/div/div[10]/grid-cell-render-hyperlink/s4-hyperlink/a/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>0b050eb2-7577-45b6-ab5d-b1da98070f28</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>edit ng-star-inserted</value>
      <webElementGuid>67d692d4-e44f-4e09-800f-983943860ef1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cdk-accordion-child-1&quot;)/div[@class=&quot;mat-expansion-panel-body ng-tns-c182-7&quot;]/div[@class=&quot;ng-tns-c182-7&quot;]/div[1]/s4-grid[@id=&quot;offnotestab&quot;]/div[@id=&quot;gridContainer&quot;]/ag-grid-angular[@id=&quot;offnotestab&quot;]/div[@class=&quot;ag-root-wrapper ag-layout-auto-height ag-ltr&quot;]/div[@class=&quot;ag-root-wrapper-body ag-layout-auto-height ag-focus-managed&quot;]/div[@class=&quot;ag-root ag-unselectable ag-layout-auto-height&quot;]/div[@class=&quot;ag-body-viewport ag-layout-auto-height ag-row-animation&quot;]/div[@class=&quot;ag-center-cols-clipper&quot;]/div[@class=&quot;ag-center-cols-viewport&quot;]/div[@class=&quot;ag-center-cols-container&quot;]/div[@class=&quot;ag-row-even ag-row ag-row-level-0 middle ag-row-position-absolute ag-row-first ag-row-last ag-row-selected ag-row-focus ag-row-hover&quot;]/div[@class=&quot;ag-cell-value ag-cell ag-cell-not-inline-editing ag-cell-normal-height hyperlinkCellOfhref ag-cell-focus ag-cell-range-selected ag-cell-range-selected-1 ag-cell-range-single-cell&quot;]/grid-cell-render-hyperlink[@class=&quot;ng-star-inserted&quot;]/s4-hyperlink[@class=&quot;edit ng-star-inserted&quot;]/a[@class=&quot;grid-hyperlink ng-star-inserted&quot;]/span[@class=&quot;edit ng-star-inserted&quot;]</value>
      <webElementGuid>8ef7dcb9-85f3-45c4-bc5a-27f8465652e3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ag-grid-angular[@id='offnotestab']/div/div[2]/div[2]/div[3]/div[2]/div/div/div/div[10]/grid-cell-render-hyperlink/s4-hyperlink/a/span</value>
      <webElementGuid>38ab3ebf-7a69-4d55-8bb2-ddb83a153e09</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='DWIVEDI, ANJU'])[1]/following::span[3]</value>
      <webElementGuid>a22b31ad-d91c-4a0d-ae0c-1c481c895dd2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='To find locator'])[1]/following::span[3]</value>
      <webElementGuid>2838d1d5-2835-475e-ad8b-4d6859a859d5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='to'])[2]/preceding::span[11]</value>
      <webElementGuid>6015a1ad-7970-4dea-8589-6ca4c1a98e74</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='of'])[3]/preceding::span[13]</value>
      <webElementGuid>5a4791ea-a381-451f-830b-5f4d947e9305</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[10]/grid-cell-render-hyperlink/s4-hyperlink/a/span</value>
      <webElementGuid>d3a6d73a-48f3-4ae3-9190-4b643f6eb2dc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
