<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>ANT Result checkbox</name>
   <tag></tag>
   <elementGuidId>a2828b8f-227a-4bac-a229-f340887baa84</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#textcheck_box3 > label.mat-checkbox-layout > span.mat-checkbox-inner-container</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//mat-checkbox[@id='textcheck_box3']/label/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>087bd530-aa56-4b52-9466-e8ddc135afc1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mat-checkbox-inner-container</value>
      <webElementGuid>d268c782-05e8-4feb-b993-5907df75ccfe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cdk-accordion-child-5&quot;)/div[@class=&quot;mat-expansion-panel-body ng-tns-c182-38&quot;]/div[@class=&quot;ng-tns-c182-38&quot;]/s4-checkbox[@id=&quot;textcheck_box3&quot;]/mat-checkbox[@id=&quot;textcheck_box3&quot;]/label[@class=&quot;mat-checkbox-layout&quot;]/span[@class=&quot;mat-checkbox-inner-container&quot;]</value>
      <webElementGuid>31c2ba26-8d00-4b97-a558-c199595c32ff</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//mat-checkbox[@id='textcheck_box3']/label/span</value>
      <webElementGuid>69ce98aa-f315-4ce3-bd89-1197455b11b1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Case Note Text'])[2]/following::span[12]</value>
      <webElementGuid>6770064f-965d-4bc8-9f01-ca8bb381b2e8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//s4-checkbox[2]/mat-checkbox/label/span</value>
      <webElementGuid>faccbd29-e243-475d-99f1-908d297b9095</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
