<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Case Review checkbox</name>
   <tag></tag>
   <elementGuidId>4146fe8e-0ada-44fa-ae5e-f47c02221aff</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#textcheck_box5 > label.mat-checkbox-layout > span.mat-checkbox-label</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//mat-checkbox[@id='textcheck_box5']/label/span[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>4e1dd14c-0274-46bf-a488-47a872b72af2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mat-checkbox-label</value>
      <webElementGuid>4ce5879f-f1b0-433c-a837-f0047e04c116</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>  Case Review </value>
      <webElementGuid>787deea6-dd54-47ce-80bf-15bb4ff808a0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cdk-accordion-child-5&quot;)/div[@class=&quot;mat-expansion-panel-body ng-tns-c182-38&quot;]/div[@class=&quot;ng-tns-c182-38&quot;]/s4-checkbox[@id=&quot;textcheck_box5&quot;]/mat-checkbox[@id=&quot;textcheck_box5&quot;]/label[@class=&quot;mat-checkbox-layout&quot;]/span[@class=&quot;mat-checkbox-label&quot;]</value>
      <webElementGuid>766b3278-20d6-4281-87d7-96b836740bb2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//mat-checkbox[@id='textcheck_box5']/label/span[2]</value>
      <webElementGuid>02eb179b-4b81-46d7-9643-abdc7a5722b9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//s4-checkbox[3]/mat-checkbox/label/span[2]</value>
      <webElementGuid>758082f3-ac58-4cd3-a6e7-b2914696ee21</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = '  Case Review ' or . = '  Case Review ')]</value>
      <webElementGuid>a4a2d9f2-da28-49e7-9848-54ffc7723c03</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
