<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Checkbox_Attempt Contact</name>
   <tag></tag>
   <elementGuidId>860fe3a9-3eba-435d-9776-41e054f0d8c3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#textcheck_box1 > label.mat-checkbox-layout > span.mat-checkbox-inner-container</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//mat-checkbox[@id='textcheck_box1']/label/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>3c00dcf1-f637-40c9-9c83-c772f7656bb3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mat-checkbox-inner-container</value>
      <webElementGuid>2d2816b9-12d5-4ceb-9066-e357a910a6ba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cdk-accordion-child-5&quot;)/div[@class=&quot;mat-expansion-panel-body ng-tns-c182-38&quot;]/div[@class=&quot;ng-tns-c182-38&quot;]/s4-checkbox[@id=&quot;textcheck_box1&quot;]/mat-checkbox[@id=&quot;textcheck_box1&quot;]/label[@class=&quot;mat-checkbox-layout&quot;]/span[@class=&quot;mat-checkbox-inner-container&quot;]</value>
      <webElementGuid>eef159a9-e02b-4a51-bac6-37aa6de3a4b1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//mat-checkbox[@id='textcheck_box1']/label/span</value>
      <webElementGuid>bb248831-2a71-40a3-9803-083d7f2a061d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Case Note Text'])[2]/following::span[4]</value>
      <webElementGuid>1f85eafe-0a0d-4e19-a208-1bbf8df9018e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Amend Case Note'])[1]/following::span[4]</value>
      <webElementGuid>c80cc633-40d8-4384-a792-3538ab5f511a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//mat-expansion-panel/div/div/div[2]/s4-checkbox/mat-checkbox/label/span</value>
      <webElementGuid>0294e63a-64b9-4520-817c-b5dea27126da</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
