<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>SaveButton_Amend</name>
   <tag></tag>
   <elementGuidId>ffe7c00c-561d-45cc-90db-1b292fe56373</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;but_save&quot;]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;but_save&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;but_save&quot;]</value>
      <webElementGuid>f4733e42-7559-4e44-aea4-7c9172a2956f</webElementGuid>
   </webElementProperties>
</WebElementEntity>
