<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Add button</name>
   <tag></tag>
   <elementGuidId>665f71a8-5934-444d-94d4-99c9b802a5a6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.court-btn.controls-btn.add-btn</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@type='submit']</value>
      </entry>
      <entry>
         <key>IMAGE</key>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@Addbutton = '&lt;button _ngcontent-elm-c198=&quot;&quot; type=&quot;button&quot; class=&quot;court-btn controls-btn add-btn&quot;> &amp;nbsp; &lt;/button>']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>1d5005da-c76f-4519-bdd6-b8ab172bb2ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>f39e0e8f-fe66-489d-bfa0-4c45f4908e19</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>court-btn controls-btn add-btn</value>
      <webElementGuid>b277e0bb-bff7-44b0-a651-b2e393f145ce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>   </value>
      <webElementGuid>d345353f-ea49-4e02-9c6a-d65fa4fb1ea4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cdk-accordion-child-11&quot;)/div[@class=&quot;mat-expansion-panel-body ng-tns-c182-130&quot;]/div[@class=&quot;ng-tns-c182-130&quot;]/div[1]/s4-grid[@id=&quot;offnotestab&quot;]/div[@id=&quot;gridContainer&quot;]/div[2]/div[@class=&quot;pagination--div&quot;]/div[1]/div[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;ng-star-inserted&quot;]/button[@class=&quot;court-btn controls-btn add-btn&quot;]</value>
      <webElementGuid>26192c4d-169a-4939-a9e0-2cd5b9d954cf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>Addbutton</name>
      <type>Main</type>
      <value>&lt;button _ngcontent-elm-c198=&quot;&quot; type=&quot;button&quot; class=&quot;court-btn controls-btn add-btn&quot;> &amp;nbsp; &lt;/button></value>
      <webElementGuid>6227db44-9d93-422c-8a98-c4aa03ffd3c5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@type='submit']</value>
      <webElementGuid>e64fbff3-cf8f-4361-ab27-5124e9ae6190</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>(//div[@id='gridContainer']/div[2]/div/div/div/div/button)[5]</value>
      <webElementGuid>5ab28964-fa10-4429-a27e-dce7920c74fa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='of'])[4]/following::button[1]</value>
      <webElementGuid>e981d029-b6e5-4c8e-b2ba-21754f29f556</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Page'])[2]/following::button[1]</value>
      <webElementGuid>52417b43-1d79-4a4c-a6c2-da40c787e7e4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Rows per page'])[2]/preceding::button[3]</value>
      <webElementGuid>660a6ae5-7a0f-4e51-8d8e-a0060773a435</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/s4-grid/div/div[2]/div/div/div/div/button</value>
      <webElementGuid>c022ffb3-4d5d-4e7b-a05f-f69d34b9855a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'submit' and (text() = '   ' or . = '   ')]</value>
      <webElementGuid>466deba0-0f5e-43bf-9943-ec72b2335280</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
