<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>NoteSubType</name>
   <tag></tag>
   <elementGuidId>b136d72d-ea14-4464-82ed-b78f47d0c103</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#mat-option-209 > span.mat-option-text > li > span.ng-star-inserted</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//mat-option[@id='mat-option-209']/span/li/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>a59151e0-7b65-425a-b1d7-566864b75cbb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-star-inserted</value>
      <webElementGuid>6e6e39c0-ddd1-453f-abd1-4d65c30c5aa0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Sub Casenote 02</value>
      <webElementGuid>23f4a976-cbd9-4304-9834-d6ecc393a12d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mat-option-209&quot;)/span[@class=&quot;mat-option-text&quot;]/li[1]/span[@class=&quot;ng-star-inserted&quot;]</value>
      <webElementGuid>3424eab2-3f65-4947-b489-e81daf0fb224</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//mat-option[@id='mat-option-209']/span/li/span</value>
      <webElementGuid>605ddbac-e7ea-4718-ac5a-b8de8d12e8c9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='SCN01'])[1]/following::span[2]</value>
      <webElementGuid>a7f8a83c-3801-4c90-8ee0-b83afd469685</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sub Casenote 01'])[1]/following::span[3]</value>
      <webElementGuid>7702dcc5-acda-4d74-9243-4a6d960ff9e3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='SCN02'])[1]/preceding::span[1]</value>
      <webElementGuid>4667a113-935c-4c07-8811-1f43a73cef17</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Sub Casenote 02']/parent::*</value>
      <webElementGuid>9a5425a7-e13a-4a3e-afd6-2efc8c878fd0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//mat-option[3]/span/li/span</value>
      <webElementGuid>29de5165-b4a4-461d-bf7f-6f89d457592b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Sub Casenote 02' or . = 'Sub Casenote 02')]</value>
      <webElementGuid>c5db638b-c143-4b2d-ad5e-dc70c626a553</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
