<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Conditions_button</name>
   <tag></tag>
   <elementGuidId>555ba271-7b54-4338-9f5d-766f1d412c9c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//s4-button/button[@id=&quot;but_conditions&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//s4-button/button[@id=&quot;but_conditions&quot;]</value>
      <webElementGuid>4ec2b6c6-17ab-4d1e-bdf9-4766ffba6725</webElementGuid>
   </webElementProperties>
</WebElementEntity>
