<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>MenuIcon</name>
   <tag></tag>
   <elementGuidId>e5022a79-c6ab-495d-b12c-43df3ac0d19b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>mat-icon.mat-icon.notranslate.matIcon.material-icons.mat-icon-no-color.ng-star-inserted</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//body[@id='s4MainBody']/app-root/app-home/mat-toolbar/div/div/div/button/span/span/mat-icon</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>mat-icon</value>
      <webElementGuid>35588161-80b3-4dfb-8b9b-961b7364bfff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>3d40487f-5c01-4b51-87f9-c4e1e7ca77fc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mat-icon notranslate matIcon material-icons mat-icon-no-color ng-star-inserted</value>
      <webElementGuid>414b0633-cca3-4db6-974d-1bec4830474d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-hidden</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>b95e7e49-1b4b-4c65-a716-697291ab016e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-mat-icon-type</name>
      <type>Main</type>
      <value>font</value>
      <webElementGuid>c04a848a-1b8f-4c01-a09c-de635986c331</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>menu</value>
      <webElementGuid>a0407acf-95e0-4945-95dc-cf83cef8a72d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;s4MainBody&quot;)/app-root[1]/app-home[@class=&quot;ng-star-inserted&quot;]/mat-toolbar[@class=&quot;mat-toolbar s4-header mat-primary mat-toolbar-single-row&quot;]/div[@class=&quot;s4-header-center-align s4-toolbar&quot;]/div[@class=&quot;s4-header-center-align&quot;]/div[@class=&quot;s4-app-logo&quot;]/button[@class=&quot;mat-focus-indicator s4-sidenav-button mat-button mat-button-base cdk-focused cdk-mouse-focused&quot;]/span[@class=&quot;mat-button-wrapper&quot;]/span[@class=&quot;drawer ng-star-inserted&quot;]/mat-icon[@class=&quot;mat-icon notranslate matIcon material-icons mat-icon-no-color ng-star-inserted&quot;]</value>
      <webElementGuid>66d7743f-df28-41ee-a16d-01c0aaaf7420</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//body[@id='s4MainBody']/app-root/app-home/mat-toolbar/div/div/div/button/span/span/mat-icon</value>
      <webElementGuid>ac8c367c-27db-4c4f-a8d8-aa20a39ae041</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Elite 5.0 22:50'])[1]/preceding::mat-icon[1]</value>
      <webElementGuid>99b5fe13-e1da-485d-aa69-efbbfe77b99f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='HOBART RECEPTION PRISON'])[1]/preceding::mat-icon[2]</value>
      <webElementGuid>777edbd0-84ea-49b0-8a8d-34c9a96cc2d4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='menu']/parent::*</value>
      <webElementGuid>c72eb007-5966-4c5a-a54b-4ba911d29431</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//mat-icon</value>
      <webElementGuid>72f9a730-2116-43bf-ac75-a70e150b6945</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//mat-icon[(text() = 'menu' or . = 'menu')]</value>
      <webElementGuid>ccd6312c-2da0-4392-b842-8b099c80f5e5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
