<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>AdmissionSaveButton</name>
   <tag></tag>
   <elementGuidId>2ff9336f-3da3-4f9a-bd23-96b6cc504bd1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//button[@id='butsave']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//button[@id='butsave']</value>
      <webElementGuid>354f4718-8f5d-437b-8e95-4d01f22f39a7</webElementGuid>
   </webElementProperties>
</WebElementEntity>
