<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Calendar_year</name>
   <tag></tag>
   <elementGuidId>5794242a-bb9d-44c1-b2e6-d7628e9a7057</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//button[@aria-label=&quot;1993&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//button[@aria-label=&quot;1993&quot;]</value>
      <webElementGuid>233afd6b-aa2b-4862-866d-83f9238f64de</webElementGuid>
   </webElementProperties>
</WebElementEntity>
