<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>CreateNewOffender_button</name>
   <tag></tag>
   <elementGuidId>b8b2bc8d-2ad8-45b5-b7c3-2eb0f610c8ca</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//button[@id='coffibtn']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//button[@id='coffibtn']</value>
      <webElementGuid>01fa6f00-2a49-43f7-a69e-edae70e7bf7e</webElementGuid>
   </webElementProperties>
</WebElementEntity>
