<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>CreateNewOffenderScreen</name>
   <tag></tag>
   <elementGuidId>4825657d-2bd2-43e7-b675-fb016a674fa7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//s4-pane[@screenid='OCUCOFFE']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//s4-pane[@screenid='OCUCOFFE']</value>
      <webElementGuid>b5599220-029c-43d1-8523-565a1471568b</webElementGuid>
   </webElementProperties>
</WebElementEntity>
