<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>LastNameField</name>
   <tag></tag>
   <elementGuidId>70fa6e25-9129-4985-9b40-49fda158dbb7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//div/input[@id='textnbt_last_name']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div/input[@id='textnbt_last_name']</value>
      <webElementGuid>d066dd30-aeec-4a59-823a-e2e5fa2b8fe3</webElementGuid>
   </webElementProperties>
</WebElementEntity>
