<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Retrieve_Button</name>
   <tag></tag>
   <elementGuidId>94e2a25a-d3d5-45b7-921e-890e7516b574</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//button[@id='retrbtn']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//button[@id='retrbtn']</value>
      <webElementGuid>cb25afcf-8d6a-4ea3-8371-b2ceac66bca3</webElementGuid>
   </webElementProperties>
</WebElementEntity>
