<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>PlanOfAction_AddButton</name>
   <tag></tag>
   <elementGuidId>a1f0576f-2132-4c36-8b99-97e5073e285a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//s4-grid[@id='offActionPlnV1']/div/div[2]/div/div[1]/div/div[1]/button</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//s4-grid[@id='offActionPlnV1']/div/div[2]/div/div[1]/div/div[1]/button</value>
      <webElementGuid>d3c990f6-30f2-472b-a729-3237404760f0</webElementGuid>
   </webElementProperties>
</WebElementEntity>
