<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>PlanOfAction_criminogenic</name>
   <tag></tag>
   <elementGuidId>8a94f89d-03f2-4a01-b37f-15d504093d64</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//div[@id='OFF_ACTION_PLANS_V2']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div[@id='OFF_ACTION_PLANS_V2']</value>
      <webElementGuid>edc63901-c693-4f77-85e6-5163465f44f8</webElementGuid>
   </webElementProperties>
</WebElementEntity>
