<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Elite 5.0PM_app-loading</name>
   <tag></tag>
   <elementGuidId>4332e7c2-25b7-4e8e-af65-9c2d5a4bb3fb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.app-loading</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//body[@id='s4MainBody']/app-root/app-splash-screen/div/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>29b3dfdc-5966-4a92-972a-5b1d2dc2f534</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>app-loading</value>
      <webElementGuid>2bda9e1f-010e-435e-a0f7-80ff58f74361</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;s4MainBody&quot;)/app-root[1]/app-splash-screen[1]/div[@class=&quot;app-splash-screen&quot;]/div[@class=&quot;app-loading&quot;]</value>
      <webElementGuid>e8e11692-d872-4d7d-8f6d-e671590e8f41</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//body[@id='s4MainBody']/app-root/app-splash-screen/div/div</value>
      <webElementGuid>d981d501-a79e-46e1-b74f-d9872274eaec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Elite 5.0PM'])[1]/preceding::div[2]</value>
      <webElementGuid>0f4be951-f0fb-4906-86db-cbe8f06451f4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div</value>
      <webElementGuid>bc77a95e-852a-4b38-ae3e-0bbdeb7e5f41</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
